'use strict';
const translations = {
 title:['账号定时请求','Scheduled account requests'], subtitle:['按你的计划发送最小请求，记录各账号的执行结果。','Send minimal requests on your schedule and track each account.'],
 theme:['外观','Appearance'],autoTheme:['跟随 CPA','Follow CPA'],lightTheme:['浅色','Light'],darkTheme:['深色','Dark'],
 autoLang:['跟随 CPA','Follow CPA'], language:['语言','Language'], disconnected:['未连接','Disconnected'],connected:['已连接 CPA','Connected to CPA'],native:['在 CPA 内设置','Configure in CPA'],
 login:['沿用 CPA 登录','Use your CPA login'],connecting:['正在连接 CPA 已保存的登录状态。','Connecting with your saved CPA login.'],loginHelp:['未保存登录状态时，可在 CPA 原生插件设置中修改计划。','Without a saved login, use the native CPA plugin settings.'],openSettings:['打开 CPA 插件设置','Open CPA plugin settings'],reconnect:['重新连接','Reconnect'],
 noSession:['没有可复用的登录状态，请打开 CPA 插件设置。','No saved login is available. Open CPA plugin settings.'],expired:['CPA 登录已失效，请返回 CPA 管理界面连接。','Your CPA login has expired. Reconnect in CPA.'],changed:['CPA 登录状态已变化，请重新连接。','CPA login changed. Please reconnect.'],invalidResponse:['CPA 返回了无效响应','CPA returned an invalid response'],connectFailed:['无法连接，请在 CPA 管理界面登录后重试。','Cannot connect. Sign in to CPA and retry.'],
 demo:['演示环境 · 虚拟账号与模拟请求，不消耗真实额度。','Demo · Fake accounts and simulated requests. No real quota is used.'],
 next:['下一次自动触发','Next scheduled request'],selected:['已选账号','Selected accounts'],perAccount:['每个时间点逐个触发','One request per account at each time'],state:['运行状态','Status'],daily:['每日触发时间','Daily schedule'],scheduleHelp:['各平台独立保存计划；定时请求不保证开启新的额度窗口。','Each provider has its own plan. A request does not guarantee a new quota window.'],automatic:['自动触发','Automatic requests'],addTime:['＋ 添加时间','+ Add time'],time:['触发时间','Request time'],removeTime:['删除这个时间','Remove this time'],timezone:['时区','Time zone'],zoneHelp:['可搜索全球 IANA 时区；夏令时自动处理。','Search IANA time zones. Daylight saving changes are handled automatically.'],model:['请求模型','Request model'],chooseModel:['请先选择账号，再选择模型','Select accounts, then a model'],modelHelp:['读取所选账号共同支持的模型；请求仅要求回复 OK。','Lists models shared by selected accounts. Each request asks only for OK.'],modelsLoading:['正在读取模型…','Loading models…'],modelsFailed:['模型列表读取失败，可重试刷新账号。','Could not load models. Refresh accounts to retry.'],noCommon:['未找到所选账号共同支持的模型，请调整账号选择。','No shared model found. Adjust your account selection.'],unverifiedModel:['已保存，当前列表未确认','Saved; not confirmed by current list'],
 accounts:['选择账号','Choose accounts'],accountHelp:['按套餐分组；禁用账号会跳过。未知套餐不作推断。','Grouped by plan. Disabled accounts are skipped; unknown plans are not inferred.'],refreshAccounts:['刷新账号与模型','Refresh accounts and models'],selectGroup:['选择整组','Select group'],clearGroup:['取消整组','Clear group'],unknown:['未知套餐','Unknown plan'],noAccounts:['CPA 中暂无此类账号','No accounts for this provider in CPA'],missing:['已移除','Removed'],disabled:['已禁用','Disabled'],unavailable:['暂不可用','Unavailable'],ready:['可触发','Ready'],save:['保存计划','Save plan'],run:['立即触发一次','Run once now'],dirty:['有未保存的修改','Unsaved changes'],saveFirst:['请先保存计划，再触发选中的账号','Save the plan before running it'],saved:['计划已保存，新的时间已经生效','Plan saved and applied'],notApplied:['配置已保存，但运行时尚未生效；请刷新检查','Configuration saved but not yet applied. Refresh to check'],started:['已开始逐账号触发','Started requests for selected accounts'],maxTimes:['每天最多设置 24 个时间','Up to 24 times per day'],switchDirty:['请先保存当前平台的修改，再切换平台','Save changes before switching providers'],
 history:['最近触发记录','Recent requests'],quotaHelp:['只显示已确认的上游重置时间；Antigravity 恢复机制暂未确认。','Only confirmed upstream reset times are shown. Antigravity reset behavior is unverified.'],refresh:['刷新','Refresh'],account:['账号','Account'],at:['计划 / 触发时间','Scheduled / request time'],result:['结果','Result'],reset:['实际重置时间','Confirmed reset time'],footnote:['CPA 必须持续运行。错过的任务不补发；五小时与周额度由上游决定。','CPA must stay running. Missed runs are not replayed. Quota windows and weekly limits are controlled upstream.'],footer:['计划与结果保存在 CPA 服务器，时间按所选时区执行。','Plans and results are stored on the CPA server. Times use the selected time zone.'],
 inspect:['需要检查','Needs attention'],running:['正在触发','Running'],paused:['已暂停','Paused'],waiting:['等待触发','Scheduled'],chooseAccounts:['等待选择账号','Choose accounts'],saveAccounts:['勾选账号后保存计划','Select accounts and save'],timesPerDay:['每天 {n} 个时间点','{n} times per day'],emptyHistory:['还没有触发记录','No requests yet'],manual:['手动触发','Manual'],scheduled:['自动触发','Scheduled'],success:['成功','Success'],failed:['失败','Failed'],skipped:['已跳过','Skipped'],missed:['已错过','Missed'],uncertain:['待确认','Uncertain'],unconfirmed:['未确认','Unconfirmed'],upstreamWindow:['上游五小时窗口','Upstream five-hour window'],metadataFailed:['套餐信息暂不可用，账号显示为未知套餐。','Plan metadata unavailable; accounts are shown as unknown.'],quotaUnknown:['Antigravity：请求成功不代表额度充值或新窗口启动，恢复机制等待实际观察。','Antigravity: a successful request does not prove quota replenishment or a new window. Reset behavior remains to be observed.']
};
const backendEnglish={
 '正在触发':'Running', '计划已更改，本次未发送':'Plan changed; no request sent', '插件未启用':'Plugin disabled', '定时触发已暂停':'Schedule paused', '请先选择账号并保存配置':'Select accounts and save first', '已有触发任务正在运行':'A request batch is already running',
 '无法获取账号列表，本次未发送':'Could not read accounts; no request sent', '已错过触发时间，本次不补发':'Scheduled time missed; no replay', '账号已不在 CPA 中，本次未发送':'Account removed; no request sent', '账号已禁用，本次未发送':'Account disabled; no request sent',
 '请求成功，已读取五小时窗口的重置时间':'Request succeeded; five-hour reset time received', '请求成功，未获取到五小时重置时间':'Request succeeded; five-hour reset time unavailable', '请求成功；额度恢复机制及时间未确认':'Request succeeded; quota reset behavior and time unverified',
 'CPA 返回成功状态，但没有有效模型回复；不会自动重复发送':'CPA returned success without a valid model reply; no automatic retry', '账号认证失败或无模型权限，本次触发失败':'Authentication failed or model access denied', '账号额度不足或上游限流，本次触发失败':'Quota exhausted or upstream rate limited', '模型或请求不被上游支持，本次触发失败':'Unsupported model or request', 'CPA 或上游请求失败，请检查账号状态；不会自动重复发送':'CPA or upstream request failed; no automatic retry', '上次运行中断，结果不确定；不会自动重复发送':'Previous run interrupted; outcome uncertain, no automatic retry', '上一次触发尚未结束或计划已更改，本次未发送':'Previous run still active or plan changed; no request sent',
 '请选择有效的 IANA 时区，例如 Asia/Shanghai':'Select a valid IANA time zone', '每天最多设置 24 个触发时间':'Up to 24 times per day', '开启定时触发时至少需要一个时间':'Add a time before enabling the schedule', '触发时间必须使用 HH:MM 格式':'Use HH:MM for scheduled times', '触发时间不能重复':'Duplicate times are not allowed', '账号 ID 无效':'Invalid account ID', '最多选择 256 个账号':'Select up to 256 accounts', '请输入有效的模型名称':'Select a valid model', '触发记录损坏，已停止自动触发，避免重复发送':'State file is corrupt; requests stopped to prevent duplicates', '无法保存触发记录，已停止发送':'Could not save state; requests stopped', '无法从 CPA 获取账号列表':'Could not read CPA accounts'
};
